# Build settings
markdown: redcarpet
highlighter: pygments
#gems:
#  - jemoji
redcarpet:
  extensions:
    - tables
    - autolink
    - no_intra_emphasis
    - strikethrough 
    - fenced_code_blocks

